version: $(LibraryVersion).{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(LibraryVersion).0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'
environment:
  LibraryVersion: 0.9.2
build:
  verbosity: minimal