# build variables
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  LibraryVersion: 0.9.2
  matrix:
    - SignAssembly: true
      Signing: Signed
    - SignAssembly: false
      Signing: Unsigned
  
# versioning
version: $(LibraryVersion).{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(LibraryVersion).0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# pre-requisites
install:
  - ps: >
      Write-Host "Installing WinZip into $env:ProgramData\WinZip\...";
      $winzipUrl = 'http://download.winzip.com/winzip195-64.msi';
      $winzipCommand = 'http://download.winzip.com/wzcline40-64.exe';
      Invoke-WebRequest $winzipUrl -OutFile winzip.msi;
      Invoke-WebRequest $winzipCommand -OutFile wzcline.zip;
      msiexec /i winzip.msi /qn ADDDESKTOPICON=0 ADDSTARTMENU=0 INSTALLCMD="/noc4u /notip /autoinstall";
      regedit /S winini.reg;
      Copy-Item winzip.addon -Force "$env:ProgramData\WinZip\";
      7za x -y wzcline.zip -o"$env:ProgramFiles\WinZip\";
      
      Write-Host "Installing info-zip into $env:ProgramFiles\infozip.org\..."
      $infoZipUrl = 'ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn.zip'
      $infoUnzipUrl = 'ftp://ftp.info-zip.org/pub/infozip/win32/unz600xn.exe'
      Invoke-WebRequest $infoZipUrl -OutFile infozip.zip
      Invoke-WebRequest $infoUnzipUrl -OutFile infounzip.zip
      7za x -y infozip.zip -o"$env:ProgramFiles\infozip.org\"
      7za x -y infounzip.zip -o"$env:ProgramFiles\infozip.org\"
      
      Write-Host "Installing 7-zip into $env:ProgramFiles\7-zip\..."
      $sevenZipUrl = 'http://www.7-zip.org/a/7z920-x64.msi'
      Invoke-WebRequest $sevenZipUrl -OutFile 7z.msi
      msiexec /i 7z.msi /qn ADDDESKTOPICON=0 ADDSTARTMENU=0

# build
matrix:
  fast_finish: true
branches:
  only:
    - master
before_build:
  - nuget restore src\Zip.Portable.sln
build: 
  project: src\Zip.Portable.sln 
  verbosity: normal

# tests
test:
  assemblies:
    - '**\*.Tests.dll'
#  categories:
#    - CI

# artifacts
artifacts: 
  - path: src\BZip2.Portable\bin\$(configuration)\$(Signing)\
    name: BZip2.Portable-$(configuration)-$(Signing)-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: src\Zip.Portable\bin\$(configuration)\$(Signing)\
    name: Zip.Portable-$(configuration)-$(Signing)-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: src\Zip.Portable.PlatformSupport\bin\$(configuration)\$(Signing)\
    name: Zip.Portable.PlatformSupport-$(configuration)-$(Signing)-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: src\Zip.Portable.Platform.PCLStorage\bin\$(configuration)\$(Signing)\
    name: Zip.Portable.Platform.PCLStorage-$(configuration)-$(Signing)-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
